name=input("what is your name?")
input()
print(f"Hello {name}")
input()
print("Im going to tell you some jokes")
input()
print("Ok here we go")
input()
print("Why was the skeleton scared to cross the road?")
input()
print("Because he had not guts!!")
input()
print("HAHAHAHAH")
input()
print("I have more")
input()
print("what do you call something that has 4 wheels and flies?")
input()
input()
print("A Garbage truck!!")
