print("We are going to play a game called 2 truths and 1 lie")
input()
print("How this works is I say 3 things")
input()
print("2 are truths and one is a lie")
input()
print("Okay lets start")
input()
print("I have one pet")
input()
print("I have been to 8 countries")
input()
print("My favorite food is pizza")
input()
print("Which one was the lie?")
input()
print("The lie was that i have been to 8 countries")
input()
print("I have only been to 6")
input()
print("Thanks for playing")
print("Making more so")