print("Welcome!")
name = input("Whats your name?")
print(f"Hello {name}")
color = input("What is your favorite color?")
print(f"Thats cool my favorite color is also {color}")
print("We have so much in common!")
input("")
print("Okay now time for a joke")
print("What did the left eye say to the right eye?")
input("")
print("Something in between us smells!!!")
joke = input("Did you like that joke?")
print("Thanks I made that one myself")
input("")
season = input("Guess my favorite season?")
print(f"Your right,it is {season}")
input("")
print("Thanks for playing")