print("Welcome!")
name = input("Whats your name?")
print(f"Hello {name}")
color = input("What is your favorite color?")
print(f"Thats cool my favorite color is also {color}")
print("We have so much in common!")
print("Okay now time for a joke")
joke = input("What did the right eye say to the left eye?")
print(f"")